// Core types for advice-ledger-kit.
//
// The pattern: a system makes a recommendation, a human accepts or rejects it,
// and reality later shows who was right. It is common to record the first two
// events and never close the loop on the third, so nobody measures whether
// the advice was any good.
//
// Two failure modes show up when systems DO try to close the loop:
//
//   1. No baseline. "Nothing has gone wrong since you adopted this" is treated
//      as evidence the advice worked, when a subject nobody looked at in that
//      area satisfies the same sentence, and so does a subject where nothing
//      was ever wrong to begin with.
//
//   2. No exposure alignment. Outcomes recorded on occasions when the advice
//      could not possibly have applied are counted for and against it anyway.
//      Advice gets blamed (or credited) for what happened while it was on the
//      shelf.
//
// This library guards against both. It will not grade without a BEFORE window
// that has enough observations and at least one bad one, it only lets
// outcomes where the advice could actually apply create or reverse the
// headline reading, it enforces floors on each window separately, and below
// any floor it returns machine-readable refusal codes instead of a verdict.
//
// Dates are compared as strings, so use one consistent ISO-8601 format and one
// UTC offset for every `decidedAt` and `observedAt` in a given ledger. Mixing
// 'YYYY-MM-DD' with 'YYYY-MM-DDTHH:mm:ssZ' compares wrongly, because
// '2026-01-01' sorts before '2026-01-01T00:00:00Z'.

// ---------------------------------------------------------------------------
// Ledger inputs
// ---------------------------------------------------------------------------

/**
 * Where a recommendation came from.
 *
 * 'observed'       — derived from something the system actually counted.
 * 'model-proposed' — generated by a model reasoning over the corpus. Still
 *                    gradeable here as long as it names a `checkKey`, but the
 *                    basis is carried through to the result so a caller can
 *                    hold it to a different bar (see `requireObservedBasis`).
 */
export type RecommendationBasis = 'observed' | 'model-proposed'

/** One piece of advice the system emitted, about one subject. */
export interface Recommendation {
  /** Stable identifier. A `Decision` refers back to this. */
  id: string
  /** What the advice is about: a project, a machine, a queue, an account. */
  subjectId: string
  /**
   * The thing later observations report on. This is what makes a
   * recommendation gradeable at all: without a check key, no observation can
   * be matched back to the advice, and this library refuses rather than
   * guessing. An empty or whitespace-only `checkKey` is always a refusal.
   * Matched against `Observation.checkKey` by exact string equality.
   */
  checkKey: string
  /** When the advice was made. Carried for your records; `gradeDecision` does not read it. */
  proposedAt: string
  /** Defaults to 'observed' when omitted. */
  basis?: RecommendationBasis
}

/** Whether the human took the advice. */
export type DecisionStatus = 'adopted' | 'dismissed'

/** The human's call on one recommendation, at a point in time. */
export interface Decision {
  /** Must equal `Recommendation.id`, or the grade is refused. */
  recommendationId: string
  status: DecisionStatus
  /**
   * When the call was made. Observations strictly before it form the
   * baseline, strictly after it the result; equal ones grade neither window.
   * Must be a non-empty string.
   */
  decidedAt: string
}

/** What an observation found: the thing was fine, or it was not. */
export type ObservationState = 'good' | 'bad'

/**
 * One dated reading of one check on one subject.
 *
 * There is no observation id and no deduplication: two identical rows count
 * as two readings.
 */
export interface Observation {
  /** Matched against `Recommendation.subjectId` by exact string equality. */
  subjectId: string
  /** Matched against `Recommendation.checkKey` by exact string equality. */
  checkKey: string
  /** Anything other than 'good' or 'bad' on a matching observation throws a TypeError. */
  state: ObservationState
  /** Compared to `decidedAt` as a string. Must be non-empty on a matching observation. */
  observedAt: string
  /**
   * Whether the recommendation could actually have applied on this occasion.
   *
   * THIS FLAG IS LOAD-BEARING. Only observations with `exposed === true` may
   * create or reverse the headline verdict. `false` and omitted are both
   * treated as not-exposed, deliberately: an unanswered exposure question is
   * not a confirmed exposure, and letting it act like one is exactly the bug
   * this field exists to prevent.
   *
   * On observations BEFORE the decision, this flag is ignored — the advice was
   * not in force yet, so there is nothing it could have been exposed to.
   */
  exposed?: boolean
}

// ---------------------------------------------------------------------------
// Grading a decision
// ---------------------------------------------------------------------------

/**
 * 'holding'     — every floor is met and the exposed post-decision window has
 *                 fewer than `refuteThreshold` bad observations.
 * 'not-holding' — every floor is met and the exposed post-decision window has
 *                 at least `refuteThreshold` bad observations.
 * 'refused'     — a floor or a structural check failed. Read `refusalCodes`.
 *
 * The verdict is a count against `refuteThreshold`, not a comparison of bad
 * rates. 'holding' can come back while the bad rate went up (1 of 10 before,
 * 1 of 3 since); read `badRateDelta` for the direction.
 */
export type DecisionVerdict = 'holding' | 'not-holding' | 'refused'

/**
 * Why a grade was refused. An array of these, never a boolean and never a
 * vague "unproven" string, so a caller can branch on the specific gap and
 * tell the user what would fix it.
 */
export type GradeRefusalCode =
  /** Floor: fewer pre-decision observations than `minBaselineObservations`. */
  | 'baseline_below_minimum'
  /** Floor: fewer post-decision observations (exposed or not) than `minResultObservations`. */
  | 'result_below_minimum'
  /**
   * Floor: fewer exposed post-decision observations than
   * `minExposedResultObservations`. Fires whether or not any unexposed
   * post-decision observations exist.
   */
  | 'exposed_result_below_minimum'
  /**
   * Floor: fewer bad pre-decision observations than
   * `minBaselineBadObservations`. With a full baseline this means the problem
   * was not occurring (often enough) before the decision, so its absence
   * afterward is not evidence the advice did anything. An empty baseline
   * also triggers it (whenever this floor is 1 or more), alongside
   * 'baseline_below_minimum'.
   */
  | 'baseline_lacks_negative_signal'
  /** Structural: the recommendation's `checkKey` is empty, whitespace-only, or not a string. */
  | 'no_gradeable_check_key'
  /** Structural: `requireObservedBasis` is on and the basis is 'model-proposed'. */
  | 'basis_not_gradeable'
  /** Structural: `decision.recommendationId` does not equal `recommendation.id`. */
  | 'decision_recommendation_mismatch'

/** Caller-supplied floors and thresholds. Every field has a default. */
export interface GradeConfig {
  /** Minimum pre-decision observations. Default 3. */
  minBaselineObservations?: number
  /** Minimum post-decision observations of any exposure. Default 3. */
  minResultObservations?: number
  /** Minimum post-decision observations where the advice could apply. Default 3. */
  minExposedResultObservations?: number
  /**
   * Minimum 'bad' observations in the baseline. Default 1. A baseline with no
   * bad readings gives the advice nothing to have improved. Setting this equal
   * to `proposeThreshold` is the stricter and more coherent choice.
   */
  minBaselineBadObservations?: number
  /**
   * How many bad observations it took to justify emitting this recommendation
   * in the first place. Default 2. This library does not enforce that the
   * proposal actually cleared this bar; it uses it to derive a symmetric
   * refute bar.
   */
  proposeThreshold?: number
  /**
   * How many bad exposed post-decision observations it takes to overturn the
   * decision. Defaults to `proposeThreshold`, i.e. symmetric.
   *
   * Setting this BELOW `proposeThreshold` throws. Refuting more cheaply than
   * you proposed is not conservatism, it is a thumb on the scale — see the
   * README section "Why asymmetry in the wrong direction is a bug".
   */
  refuteThreshold?: number
  /** When true, a 'model-proposed' recommendation is refused. Default false. Must be a boolean. */
  requireObservedBasis?: boolean
}

/** `GradeConfig` with every default filled in. Echoed in every result. */
export interface ResolvedGradeConfig {
  minBaselineObservations: number
  minResultObservations: number
  minExposedResultObservations: number
  minBaselineBadObservations: number
  proposeThreshold: number
  refuteThreshold: number
  requireObservedBasis: boolean
}

/** Plain counts over one window of observations. */
export interface WindowReading {
  observations: number
  bad: number
  good: number
  /** `bad / observations`, rounded to 3 places (exact halves up). `null` on an empty window. */
  badRate: number | null
}

/**
 * The same post-decision window read WITHOUT exposure alignment.
 *
 * This is deliberately not the headline and can never become it. It is here so
 * a caller can show the raw picture, and so the gap between it and the
 * headline is visible rather than hidden.
 */
export interface SecondaryReading extends WindowReading {
  label: 'secondary-not-the-headline'
  /**
   * What the verdict would have been if exposure were ignored: the same
   * floors and refute bar, applied with every post-decision observation
   * treated as exposed. 'refused' when that exposure-blind grade would also
   * fail a floor, and on every structural refusal.
   */
  wouldBeVerdict: DecisionVerdict
  interpretation: 'exposure_unaligned_descriptive_only'
  note: string
}

/**
 * The result of grading one decision against what happened afterwards.
 *
 * On a floor refusal the windows hold real counts. On a structural refusal
 * ('decision_recommendation_mismatch', 'no_gradeable_check_key',
 * 'basis_not_gradeable') nothing is read: `baseline`, `result` and
 * `secondary` are all-zero placeholders with null rates, and
 * `atBoundaryObservations` is 0. Those zeros are not measurements.
 */
export interface DecisionGrade {
  verdict: DecisionVerdict
  /**
   * Empty when a verdict was reached. Never empty when `verdict` is 'refused'.
   * Structural codes short-circuit and appear without floor codes; floor codes
   * accumulate, every unmet floor listed.
   */
  refusalCodes: GradeRefusalCode[]
  recommendationId: string
  subjectId: string
  checkKey: string
  status: DecisionStatus
  basis: RecommendationBasis
  decidedAt: string
  /** All observations before `decidedAt`. Exposure is not applied here. */
  baseline: WindowReading
  /**
   * The headline window: post-decision observations with `exposed === true`,
   * and only those.
   */
  result: WindowReading
  /**
   * `result.badRate - baseline.badRate`, using the two rounded rates shown, so
   * it can differ from the unrounded difference by up to 0.001. Negative means
   * the rate went down. `null` when either window is empty. Does not affect
   * the verdict.
   */
  badRateDelta: number | null
  /** All post-decision observations, exposed or not. Explicitly not the headline. */
  secondary: SecondaryReading
  /**
   * Observations timestamped exactly at `decidedAt`. They belong to neither
   * window — the decision happened during them — so they are counted and
   * reported but never graded.
   */
  atBoundaryObservations: number
  thresholds: ResolvedGradeConfig
  method: 'exposure_aligned_before_after_on_matched_check'
  interpretation: 'association_not_causation'
}

// ---------------------------------------------------------------------------
// Divergence between two judges
// ---------------------------------------------------------------------------

/**
 * One occasion where two independent judges rated the same object, and
 * possibly a later outcome that settles which of them was right.
 *
 * All three are free-form strings from a vocabulary the caller defines. They
 * are compared by exact equality (case and whitespace included), so use one
 * canonical spelling per judgment. A judgment that is missing, empty, or not
 * a string counts as "did not speak"; a whitespace-only string counts as a
 * judgment. A missing or empty `laterOutcome` means "not settled yet".
 */
export interface JudgmentPair {
  /** What the system said. */
  engineJudgment: string
  /** What the human said. */
  humanJudgment: string
  /** What actually turned out to be the case, when that is known yet. */
  laterOutcome?: string
  /** Optional bucket, used by the default `groupBy`. */
  group?: string
  /**
   * Optional identifier, carried through into `examples`. Not used for
   * deduplication: pairs sharing an id are counted separately.
   */
  id?: string
}

/** Why a divergence or calibration reading was refused. */
export type DivergenceRefusalCode =
  /** Fewer comparable pairs (both judges spoke) than `minComparablePairs`. */
  | 'comparable_pairs_below_minimum'
  /** Fewer disagreements than `minDivergentCount` (including zero). */
  | 'divergent_count_below_minimum'
  /**
   * The exact share `divergentCount / comparablePairs` is below
   * `minDivergentRate`, or there are no comparable pairs so no rate exists.
   * Checked independently of the count floor.
   */
  | 'divergent_rate_below_minimum'
  /** Fewer disagreements with a `laterOutcome` than `minResolvedDivergent`. */
  | 'resolved_divergent_below_minimum'

/** Caller-supplied floors for divergence. Every field has a default. */
export interface DivergenceConfig {
  /** Minimum pairs where both judges spoke. Default 10. */
  minComparablePairs?: number
  /** Minimum disagreements. Default 3. */
  minDivergentCount?: number
  /** Minimum disagreement share of comparable pairs. Default 0.05. */
  minDivergentRate?: number
  /** Minimum disagreements with a later outcome, before naming who was right. Default 3. */
  minResolvedDivergent?: number
  /** How many divergent pairs to carry through as examples. Default 10. 0 allowed. */
  exampleLimit?: number
  /**
   * Arbitrary caller-supplied bucketing. Return `null` (or `undefined`) to
   * leave a pair out of the per-group breakdown; it still counts in `overall`.
   * Any other non-string return throws a TypeError. Called once per pair.
   * Defaults to the pair's own `group`.
   */
  groupBy?: (pair: JudgmentPair) => string | null
}

/** `DivergenceConfig` floors with defaults filled in. Echoed in every result. */
export interface ResolvedDivergenceConfig {
  minComparablePairs: number
  minDivergentCount: number
  minDivergentRate: number
  minResolvedDivergent: number
  exampleLimit: number
}

/**
 * Who turned out to be right on the occasions the two judges disagreed.
 *
 * The engine's and the human's hit rates are reported as separate numbers on
 * purpose and are never combined into a single "accuracy". Merging them
 * answers the wrong question: a system can be right most of the time overall
 * and still be wrong every single time a human bothers to overrule it, and
 * that second fact is the one worth acting on.
 */
export interface CalibrationReading {
  /** Divergent pairs that have a `laterOutcome`. */
  resolvedDivergent: number
  engineRight: number
  humanRight: number
  /** The outcome matched neither judgment. */
  neitherRight: number
  /** Each rate is its count over `resolvedDivergent`, rounded to 3 places. `null` when nothing is resolved. */
  engineRightRate: number | null
  humanRightRate: number | null
  neitherRightRate: number | null
  /**
   * Gated only by `minResolvedDivergent`. It is independent of the parent
   * report's `status`, so it can be 'reportable' on a report that is
   * 'refused' (for example, 3 settled disagreements out of 100 pairs, below
   * the rate floor). `describeDivergence` does not print calibration for a
   * refused report.
   */
  status: 'reportable' | 'refused'
  refusalCodes: DivergenceRefusalCode[]
  note: 'engine_and_human_accuracy_reported_separately_never_merged'
}

/** Divergence over one population: the whole set, or one group within it. */
export interface DivergenceReport {
  /** The group key, or `null` for the overall report. */
  group: string | null
  /** Every pair handed in for this population. */
  totalPairs: number
  /**
   * Pairs where BOTH judges actually spoke. This is the only honest
   * denominator: pairs missing a judgment are not agreements, they are
   * occasions where disagreement was impossible.
   */
  comparablePairs: number
  agreements: number
  divergentCount: number
  /**
   * `divergentCount / comparablePairs`, rounded to 3 places for display. The
   * rate floor is checked against the exact ratio, so a rate that displays as
   * 0.05 can still be refused at a 0.05 floor. `null` when nothing is comparable.
   */
  divergentRate: number | null
  status: 'reportable' | 'refused'
  refusalCodes: DivergenceRefusalCode[]
  calibration: CalibrationReading
  /** Divergent pairs, capped at `exampleLimit`, in input order. These are your own pair objects, not copies. */
  examples: JudgmentPair[]
  interpretation: 'disagreement_is_a_signal_not_a_verdict'
}

/** The full result of `computeDivergence`. */
export interface DivergenceResult {
  overall: DivergenceReport
  /**
   * One report per distinct group key, sorted by UTF-16 code unit order
   * (Array.prototype.sort, not locale-aware). Empty when nothing grouped.
   */
  groups: DivergenceReport[]
  thresholds: ResolvedDivergenceConfig
}
